project_name: 'prune-labse-en-ru'
experiment_name: 'prune-labse-en-ru'
n_epochs: 40
accelerator: 'gpu'
device: 0
monitor_metric: 'val_mse'
monitor_mode: 'min'

model_name: 'cointegrated/LaBSE-en-ru'

pruning:
  pruning_ratio: 0.75
  global_pruning: False
  iterative_steps: 5

optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 3e-4
  weight_decay: 1e-5

scheduler: 'torch.optim.lr_scheduler.CosineAnnealingLR'
scheduler_kwargs:
  T_max: 10
  eta_min: 1e-5

losses:
  - name: 'mse'
    weight: 1.0
    loss_fn: 'torch.nn.MSELoss'
    loss_kwargs: {}

data_config:
  data_path: 'data/'
  batch_size: 16
  n_workers: 20
  train_size: 0.8
